name: Deploy website on push
on: push
jobs:
  web-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: appleboy/ssh-action@master
        with:
          host: "ssh-${{ secrets.USERNAME }}.alwaysdata.net"
          username: projetnfsecret091
          password: iCwpRiCu7(Pxzz((Ent*

 
           
